export const VERIFIED_CENTRES_SEED_DATA = [
  {
    name: 'ISHA GYM WEIGHTLIFTING SPORTS ACADEMY',
    centreType: 'Weightlifting Academy',
    contactPerson: 'S. SHANMUGAM',
    phone: '9944301212',
    displayOrder: 1,
  },
  {
    name: 'Isha Elite Weightlifting Academy',
    centreType: 'Weightlifting Academy',
    contactPerson: 'S. SHANMUGAM',
    phone: '9944301212',
    displayOrder: 2,
  },
  {
    name: 'Jai Maruti Gym',
    centreType: 'Gym',
    contactPerson: 'V. Ponnusamy',
    phone: '9789759372',
    displayOrder: 3,
  },
  {
    name: 'Raavanan Weightlifting Academy',
    centreType: 'Weightlifting Academy',
    contactPerson: 'S. VijayaRaghavan',
    phone: '7871547563',
    displayOrder: 4,
  },
  {
    name: 'Shivam Fitness',
    centreType: 'Fitness Centre',
    contactPerson: 'G. Thilagam',
    phone: '+91 9566673133',
    displayOrder: 5,
  },
  {
    name: 'Preethi Fitness',
    centreType: 'Fitness Centre',
    contactPerson: 'Preeti',
    phone: '6379616391',
    displayOrder: 6,
  },
  {
    name: 'Veerapandi South Union GYM',
    centreType: 'Gym',
    contactPerson: 'T. Gunasekaran',
    phone: '9043363527',
    displayOrder: 7,
  },
  {
    name: 'Vivekananda GYM',
    centreType: 'Gym',
    contactPerson: 'L. R. Marconi',
    phone: '9842772090',
    displayOrder: 8,
  },
  {
    name: 'Anjaneya Sports Academy',
    centreType: 'Sports Academy',
    contactPerson: 'S. Gnanavel',
    phone: '6381519954',
    displayOrder: 9,
  },
  {
    name: 'Kanjamalai Gym',
    centreType: 'Gym',
    contactPerson: 'K. Selvaraj',
    phone: '9524361421',
    displayOrder: 10,
  },
  {
    name: 'Sri Maruti Power Gym',
    centreType: 'Gym',
    contactPerson: 'S. Sakthivel',
    phone: '6380937459',
    displayOrder: 11,
  },
  {
    name: 'Success Fitness',
    centreType: 'Fitness Centre',
    contactPerson: 'S. Vijay Raghavan',
    phone: '7871547563',
    displayOrder: 12,
  },
  {
    name: 'Shri PSG Arts College',
    centreType: 'Educational Institution',
    contactPerson: 'K. Thenmozhi',
    phone: '8056728891',
    displayOrder: 13,
  },
  {
    name: 'PAAVAI Engineering College',
    centreType: 'Educational Institution',
    contactPerson: 'V. Swaminathan',
    phone: '7338962235',
    displayOrder: 14,
  },
  {
    name: 'Trinity Arts College',
    centreType: 'Educational Institution',
    contactPerson: 'V. Archana',
    phone: '7339088845',
    displayOrder: 15,
  },
];
