import { CommitteeMemberFormData } from '@/types';

export const INITIAL_OFFICIAL_COMMITTEE: CommitteeMemberFormData[] = [
  {
    name: 'L.R. Marconi',
    designation: 'President',
    position: 'President',
    description: 'Executive committee leadership of Salem District Weightlifting Association.',
    photoUrl: '',
    photoPublicId: '',
    displayOrder: 1,
    isActive: true,
  },
  {
    name: 'S. Shanmugam',
    designation: 'Secretary',
    position: 'Secretary',
    description: 'Executive committee leadership of Salem District Weightlifting Association.',
    photoUrl: '',
    photoPublicId: '',
    displayOrder: 2,
    isActive: true,
  },
  {
    name: 'G. Thilagam',
    designation: 'Treasurer',
    position: 'Treasurer',
    description: 'Executive committee leadership of Salem District Weightlifting Association.',
    photoUrl: '',
    photoPublicId: '',
    displayOrder: 3,
    isActive: true,
  },
  {
    name: 'T.V. Rajagopalan',
    designation: 'Vice-President',
    position: 'Vice-President',
    description: 'Executive committee member of Salem District Weightlifting Association.',
    photoUrl: '',
    photoPublicId: '',
    displayOrder: 4,
    isActive: true,
  },
  {
    name: 'T. Muthukumar',
    designation: 'Vice-President',
    position: 'Vice-President',
    description: 'Executive committee member of Salem District Weightlifting Association.',
    photoUrl: '',
    photoPublicId: '',
    displayOrder: 5,
    isActive: true,
  },
  {
    name: 'V. Ponnusamy',
    designation: 'Joint Secretary',
    position: 'Joint Secretary',
    description: 'Executive committee member of Salem District Weightlifting Association.',
    photoUrl: '',
    photoPublicId: '',
    displayOrder: 6,
    isActive: true,
  },
  {
    name: 'I.S. Sneha',
    designation: 'Joint Secretary',
    position: 'Joint Secretary',
    description: 'Executive committee member of Salem District Weightlifting Association.',
    photoUrl: '',
    photoPublicId: '',
    displayOrder: 7,
    isActive: true,
  },
  {
    name: 'R. Ranjithkumar',
    designation: 'Executive Member',
    position: 'Executive Member',
    description: 'Executive committee member of Salem District Weightlifting Association.',
    photoUrl: '',
    photoPublicId: '',
    displayOrder: 8,
    isActive: true,
  },
  {
    name: 'S. Revathi',
    designation: 'Executive Member',
    position: 'Executive Member',
    description: 'Executive committee member of Salem District Weightlifting Association.',
    photoUrl: '',
    photoPublicId: '',
    displayOrder: 9,
    isActive: true,
  },
  {
    name: 'K. Viknesh',
    designation: 'Executive Member',
    position: 'Executive Member',
    description: 'Executive committee member of Salem District Weightlifting Association.',
    photoUrl: '',
    photoPublicId: '',
    displayOrder: 10,
    isActive: true,
  },
  {
    name: 'S. Vijayagaravan',
    designation: 'Executive Member',
    position: 'Executive Member',
    description: 'Executive committee member of Salem District Weightlifting Association.',
    photoUrl: '',
    photoPublicId: '',
    displayOrder: 11,
    isActive: true,
  },
];
